'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import {
  createAgent,
  renameAgent,
  revokeAgent,
  updateAgentProfile,
} from '../lib/api';
import { useToast } from './ToastRegion';
import Toggle from './Toggle';

/**
 * PairAgentModal — dialog that produces the copy-text an AI agent pastes to
 * connect to this WebPilot instance. Two flows, gated by the "Set API key"
 * toggle pinned to the top of the modal body:
 *
 *   ON (default): the modal eagerly mints a paired-keys entry on open via
 *     POST /api/ui/agents. The code-block preview contains the real api_key
 *     immediately — both the explicit Copy button and a manual
 *     highlight+Ctrl+C yield a working key. The mint is "tentative": if the
 *     user closes the modal (Cancel, Esc, backdrop) without ever clicking
 *     Copy, we DELETE the entry so a casual modal-open doesn't leave a
 *     zombie agent behind. Clicking Copy flips a `committed` flag and the
 *     entry survives close.
 *
 *     While the modal is open, edits to the name (debounced ~600ms) are
 *     persisted via the existing rename endpoint; profile-dropdown changes
 *     hit the PATCH endpoint immediately. Both operate on the tentative
 *     entry — no separate "create" step.
 *
 *   OFF: copy-text instructs the agent through the classic request_pairing
 *     flow. No backend call; the name/profile inputs are hidden.
 *
 * Layout:
 *   - Title + subhead that mirrors the toggle state.
 *   - Toggle ("Set API key") at the top of the body.
 *   - Collapsible name + profile fields, visible when the toggle is ON.
 *   - Code block (clean, no overlay copy button).
 *   - Action row at the bottom: [Cancel] [Copy].
 */

const URL_PLACEHOLDER = '<port>';
const KEY_PLACEHOLDER = '<API_KEY>';
const AGENT_NAME_MAX = 60;
const RENAME_DEBOUNCE_MS = 600;

const SUBHEAD_ON = 'A key is ready — agent skips approval.';
const SUBHEAD_OFF = "Agent will request pairing — you'll approve it.";
const TOGGLE_HELP =
  'On — a key is minted now so the agent skips the approval step. ' +
  "Off — agent will request pairing and you'll approve it.";

// Small, PG, easy-to-say wordlist for autogenerated agent names. ~30 entries
// keeps the name space wide enough to avoid frequent collisions when paired
// with a 4-digit suffix (~30 * 10000 = 300k combos) without leaning on a
// dictionary file. Bias toward concrete, friendly nouns.
const AUTONAME_WORDS = [
  'panda', 'otter', 'willow', 'lyra', 'ember', 'juno', 'pixel', 'sable',
  'marlin', 'finch', 'cypress', 'harbor', 'cobalt', 'maple', 'aspen',
  'koi', 'lark', 'nimbus', 'opal', 'quartz', 'river', 'sparrow', 'tide',
  'umbra', 'vesper', 'wren', 'zephyr', 'cedar', 'fjord', 'mira',
];

function rollAutoName() {
  const word = AUTONAME_WORDS[Math.floor(Math.random() * AUTONAME_WORDS.length)];
  const digits = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
  return `Agent ${word}-${digits}`;
}

function buildPromptWithKey(port, apiKey) {
  const portStr = port ? String(port) : URL_PLACEHOLDER;
  const keyStr = apiKey || KEY_PLACEHOLDER;
  return (
`Connect to my WebPilot MCP server at http://localhost:${portStr}/sse with API key ${keyStr}.

Set both in your .mcp.json:

{
  "mcpServers": {
    "webpilot": {
      "type": "sse",
      "url": "http://localhost:${portStr}/sse",
      "headers": { "X-API-Key": "${keyStr}" }
    }
  }
}

You're already paired — no request_pairing or approval needed. Start using tools right away.`
  );
}

function buildPromptNoKey(port) {
  const portStr = port ? String(port) : URL_PLACEHOLDER;
  return (
`Connect to my WebPilot MCP server at http://localhost:${portStr}/sse.

Set the url in your .mcp.json (no key yet):

{
  "mcpServers": {
    "webpilot": {
      "type": "sse",
      "url": "http://localhost:${portStr}/sse"
    }
  }
}

You don't have an API key yet. Steps:

1. Call request_pairing with a memorable agent_name (e.g. project or client name). It returns an api_key and pairing_id.
2. Immediately set headers."X-API-Key" to that api_key in your .mcp.json — I may approve at any future moment, and the key will activate then.
3. Surface the approval URL to me, then poll check_pairing_status(pairing_id) once every 10 seconds, up to 12 attempts (2 minutes total). If unapproved after 12 tries, stop — I'll approve when ready and the key will work on the next tool call.
4. Once check_pairing_status returns approved, you're paired. Include the api_key on every tool call from then on.`
  );
}

export default function PairAgentModal({ open, onClose, port, profiles }) {
  const [closing, setClosing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [includeKey, setIncludeKey] = useState(true);
  const [agentName, setAgentName] = useState('');
  const [selectedProfile, setSelectedProfile] = useState('');
  const [generated, setGenerated] = useState(null); // { apiKey, agentName, profileId } | null
  const [submitting, setSubmitting] = useState(false);
  const [confirmFlash, setConfirmFlash] = useState(null); // string | null

  const wasOpen = useRef(open);
  const flashTimerRef = useRef(null);
  const renameTimerRef = useRef(null);
  // `committed` lives in a ref because the close-handler reads it from
  // outside React's render flow (Esc keydown, backdrop click) and a stale
  // closure on a state value would either auto-revoke a committed agent or
  // skip the revoke on a tentative one. Ref guarantees we read the latest.
  const committedRef = useRef(false);
  // Likewise `generated` is read by the unmount/close paths.
  const generatedRef = useRef(null);
  // Track the in-flight initial mint so a fast close doesn't try to revoke
  // before we have an apiKey to revoke.
  const mintInFlightRef = useRef(false);

  const toast = useToast();

  const profileList = useMemo(() => (Array.isArray(profiles) ? profiles : []), [profiles]);

  const boundProfileLabel = useMemo(() => {
    const profId = generated ? generated.profileId : selectedProfile;
    if (!profId) return '';
    const match = profileList.find((p) => p.directoryName === profId);
    return (match && (match.displayName || match.directoryName)) || profId;
  }, [generated, selectedProfile, profileList]);

  // Keep refs in sync with state so out-of-render handlers (Esc, backdrop,
  // unmount cleanup) see fresh values.
  useEffect(() => { generatedRef.current = generated; }, [generated]);

  // ---------------------------------------------------------------------------
  // Tentative-revoke helper. Called from any "user dismissed without
  // committing" path (Cancel button, Esc, backdrop, toggle flip to OFF).
  // ---------------------------------------------------------------------------
  async function revokeTentative() {
    const g = generatedRef.current;
    if (!g || !g.apiKey) return;
    if (committedRef.current) return;
    try {
      await revokeAgent(g.apiKey);
    } catch (e) {
      // Don't strand the user — log and move on. console.warn keeps this
      // out of the toast region (where it would conflict with the close).
      // eslint-disable-next-line no-console
      console.warn('PairAgentModal: failed to revoke tentative agent', e);
    }
    generatedRef.current = null;
  }

  // ---------------------------------------------------------------------------
  // Mint helper. Eagerly creates an agent and stores the result. Used on
  // modal open (toggle ON) and when the user flips the toggle back ON
  // mid-session. Errors fall back to the placeholder preview without
  // closing the modal — the static-config path still works.
  // ---------------------------------------------------------------------------
  async function mintTentative(name, profileId) {
    if (!profileId) return;
    mintInFlightRef.current = true;
    try {
      const minted = await createAgent(name, profileId);
      const next = {
        apiKey: minted.apiKey,
        agentName: minted.agentName || name,
        profileId: minted.profileId || profileId,
      };
      generatedRef.current = next;
      setGenerated(next);
    } catch (e) {
      generatedRef.current = null;
      setGenerated(null);
      const serverReason =
        (e && e.payload && (e.payload.reason || e.payload.error)) || null;
      toast.error(serverReason || (e && e.message) || 'Couldn’t create agent.');
    } finally {
      mintInFlightRef.current = false;
    }
  }

  // Mirror open → closing animation. Stay mounted until the exit anim finishes.
  useEffect(() => {
    if (wasOpen.current && !open) {
      setClosing(true);
      const id = setTimeout(() => setClosing(false), 240);
      wasOpen.current = open;
      return () => clearTimeout(id);
    }
    wasOpen.current = open;
    return undefined;
  }, [open]);

  // Reset transient state + eagerly mint each time the modal opens.
  useEffect(() => {
    if (!open) return;
    setCopied(false);
    setIncludeKey(true);
    setSubmitting(false);
    setConfirmFlash(null);
    committedRef.current = false;
    generatedRef.current = null;
    setGenerated(null);

    // Autogen the initial name; user can edit freely.
    const initialName = rollAutoName();
    setAgentName(initialName);

    // Default to the first known profile so the dropdown is never blank.
    const initialProfile = profileList.length > 0 ? profileList[0].directoryName : '';
    setSelectedProfile(initialProfile);

    // Eagerly mint so the preview shows a real key from the get-go.
    if (initialProfile) {
      mintTentative(initialName, initialProfile);
    }
    // We intentionally exclude profileList to avoid re-minting on every
    // parent re-render; the first stable value at open-time is what we want.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Esc closes (routes through the auto-revoke close handler).
  useEffect(() => {
    if (!open) return undefined;
    function onKey(e) {
      if (e.key === 'Escape') {
        e.preventDefault();
        requestClose();
      }
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Cleanup on unmount: clear timers, and best-effort revoke if the user
  // never committed (handles the "parent unmounted the modal" edge case).
  useEffect(() => {
    return () => {
      if (flashTimerRef.current) clearTimeout(flashTimerRef.current);
      if (renameTimerRef.current) clearTimeout(renameTimerRef.current);
      if (!committedRef.current && generatedRef.current && generatedRef.current.apiKey) {
        // Fire-and-forget — we're unmounting.
        revokeAgent(generatedRef.current.apiKey).catch(() => { /* swallow */ });
      }
    };
  }, []);

  if (!open && !closing) return null;

  // ---------------------------------------------------------------------------
  // Close paths
  // ---------------------------------------------------------------------------
  async function requestClose() {
    // Cancel any pending debounced rename so it doesn't fire post-revoke.
    if (renameTimerRef.current) {
      clearTimeout(renameTimerRef.current);
      renameTimerRef.current = null;
    }
    await revokeTentative();
    if (typeof onClose === 'function') onClose();
  }

  function handleBackdrop(e) {
    if (e.target === e.currentTarget) requestClose();
  }

  // ---------------------------------------------------------------------------
  // Name editing — debounced rename of the tentative entry.
  // ---------------------------------------------------------------------------
  function onNameChange(nextName) {
    setAgentName(nextName);
    if (renameTimerRef.current) {
      clearTimeout(renameTimerRef.current);
      renameTimerRef.current = null;
    }
    if (!includeKey) return;
    const g = generatedRef.current;
    if (!g || !g.apiKey) return;
    const trimmed = nextName.trim();
    if (!trimmed) return; // empty input — wait for the user to type something
    if (trimmed.length > AGENT_NAME_MAX) return;
    if (trimmed === g.agentName) return;
    renameTimerRef.current = setTimeout(async () => {
      renameTimerRef.current = null;
      try {
        await renameAgent(g.apiKey, trimmed);
        const next = { ...g, agentName: trimmed };
        generatedRef.current = next;
        setGenerated(next);
      } catch (e) {
        const serverReason =
          (e && e.payload && (e.payload.reason || e.payload.error)) || null;
        toast.error(serverReason || (e && e.message) || 'Couldn’t rename agent.');
      }
    }, RENAME_DEBOUNCE_MS);
  }

  // ---------------------------------------------------------------------------
  // Profile dropdown — immediate PATCH on the tentative entry.
  // ---------------------------------------------------------------------------
  async function onProfileChange(nextProfileId) {
    setSelectedProfile(nextProfileId);
    if (!includeKey) return;
    const g = generatedRef.current;
    if (!g || !g.apiKey) {
      // No tentative entry yet (initial mint failed) — try a fresh mint
      // against this new profile so the user can still get a key.
      if (nextProfileId) {
        await mintTentative(agentName.trim() || rollAutoName(), nextProfileId);
      }
      return;
    }
    if (nextProfileId === g.profileId) return;
    try {
      await updateAgentProfile(g.apiKey, nextProfileId);
      const next = { ...g, profileId: nextProfileId };
      generatedRef.current = next;
      setGenerated(next);
    } catch (e) {
      const serverReason =
        (e && e.payload && (e.payload.reason || e.payload.error)) || null;
      toast.error(serverReason || (e && e.message) || 'Couldn’t rebind profile.');
    }
  }

  // ---------------------------------------------------------------------------
  // Toggle flip — ON↔OFF mid-session.
  // ---------------------------------------------------------------------------
  async function onToggleChange(next) {
    setIncludeKey(next);
    setCopied(false);
    if (!next) {
      // Going OFF: revoke any tentative entry, drop the generated state.
      if (renameTimerRef.current) {
        clearTimeout(renameTimerRef.current);
        renameTimerRef.current = null;
      }
      await revokeTentative();
      setGenerated(null);
    } else {
      // Going back ON: re-mint with the CURRENT name + profile values. The
      // inputs are always visible now, so the user may have edited them
      // while the toggle was OFF — preserve that work rather than rolling
      // a fresh autoname.
      committedRef.current = false;
      const name = agentName.trim() || rollAutoName();
      const prof = selectedProfile || (profileList.length > 0 ? profileList[0].directoryName : '');
      if (prof) {
        if (!selectedProfile) setSelectedProfile(prof);
        await mintTentative(name, prof);
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Preview text — real key when minted, placeholder otherwise.
  // ---------------------------------------------------------------------------
  const previewText = includeKey
    ? buildPromptWithKey(port, generated ? generated.apiKey : null)
    : buildPromptNoKey(port);

  const subhead = confirmFlash
    ? confirmFlash
    : (includeKey ? SUBHEAD_ON : SUBHEAD_OFF);

  function scheduleConfirmFlash(message) {
    if (flashTimerRef.current) clearTimeout(flashTimerRef.current);
    setConfirmFlash(message);
    flashTimerRef.current = setTimeout(() => {
      setConfirmFlash(null);
      flashTimerRef.current = null;
    }, 3000);
  }

  // ---------------------------------------------------------------------------
  // Copy — commits the tentative entry (if any) and writes the preview text
  // to the clipboard. Stays open so the user can re-copy or tweak; explicit
  // Cancel close-path will no longer revoke since committed=true.
  // ---------------------------------------------------------------------------
  async function handleCopy() {
    if (submitting) return;
    setSubmitting(true);
    try {
      // Toggle ON path: ensure we have a key. If the initial mint failed or
      // hasn't landed yet, do a synchronous mint here so the user isn't
      // staring at the placeholder after clicking Copy.
      if (includeKey) {
        if (!generatedRef.current || !generatedRef.current.apiKey) {
          const name = agentName.trim() || rollAutoName();
          const prof = selectedProfile
            || (profileList.length > 0 ? profileList[0].directoryName : '');
          if (!prof) {
            toast.error('Pick a Chrome profile to bind the key to.');
            return;
          }
          await mintTentative(name, prof);
          if (!generatedRef.current || !generatedRef.current.apiKey) {
            // mintTentative already toasted the error.
            return;
          }
        }
        // Flush any pending rename before we commit so the server has the
        // current name when we declare the agent persistent.
        if (renameTimerRef.current) {
          clearTimeout(renameTimerRef.current);
          renameTimerRef.current = null;
          const g = generatedRef.current;
          const trimmed = agentName.trim();
          if (g && trimmed && trimmed !== g.agentName && trimmed.length <= AGENT_NAME_MAX) {
            try {
              await renameAgent(g.apiKey, trimmed);
              const next = { ...g, agentName: trimmed };
              generatedRef.current = next;
              setGenerated(next);
            } catch (_e) { /* non-fatal; the agent still exists */ }
          }
        }
      }

      const text = includeKey
        ? buildPromptWithKey(port, generatedRef.current && generatedRef.current.apiKey)
        : buildPromptNoKey(port);
      try {
        await navigator.clipboard.writeText(text);
      } catch (_e) { /* clipboard rejected; toast still wins */ }

      committedRef.current = true;
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);

      if (includeKey) {
        const g = generatedRef.current;
        const profId = (g && g.profileId) || selectedProfile;
        const match = profileList.find((p) => p.directoryName === profId);
        const profLabel = (match && (match.displayName || match.directoryName)) || profId || '';
        toast.success('Copied — agent created.');
        scheduleConfirmFlash(profLabel ? `Copied — bound to ${profLabel}.` : 'Copied.');
      } else {
        toast.success('Copied.');
        scheduleConfirmFlash('Copied.');
      }
    } finally {
      setSubmitting(false);
    }
  }

  const copyLabel = copied ? 'Copied' : (submitting ? 'Working…' : 'Copy');

  // Reference boundProfileLabel to keep the lint flow honest — it powers the
  // confirm-flash but isn't rendered as its own element.
  void boundProfileLabel;

  return (
    <div
      className={`wp-modal-backdrop${closing && !open ? ' is-closing' : ''}`}
      role="dialog"
      aria-modal="true"
      aria-labelledby="wp-pair-agent-title"
      onClick={handleBackdrop}
    >
      <div className="wp-modal wp-modal-lg">
        <h2 id="wp-pair-agent-title" className="wp-modal-title">
          Pair a new agent
        </h2>
        <div className="wp-modal-body">
          {/* Agent name — full-width row. Always visible regardless of the
              Include API key toggle so the user can pre-fill / edit ahead. */}
          <div className="wp-pair-field-row" style={{ marginBottom: 'var(--s-3)' }}>
            <label
              htmlFor="wp-pair-agent-name"
              className="wp-pair-field-label"
            >
              Agent name
            </label>
            <input
              id="wp-pair-agent-name"
              type="text"
              className="wp-input wp-input--underline"
              value={agentName}
              maxLength={AGENT_NAME_MAX}
              placeholder="e.g. Claude Code – my-project"
              onChange={(e) => onNameChange(e.target.value)}
            />
          </div>

          {/* Chrome profile + Include API key toggle — side-by-side row. */}
          <div
            style={{
              display: 'flex',
              alignItems: 'flex-end',
              gap: 'var(--s-4)',
              marginBottom: 'var(--s-4)',
            }}
          >
            <div className="wp-pair-field-row" style={{ flex: 1, marginBottom: 0 }}>
              <label
                htmlFor="wp-pair-agent-profile"
                className="wp-pair-field-label"
              >
                Chrome profile
              </label>
              <select
                id="wp-pair-agent-profile"
                className="wp-select wp-input--underline"
                value={selectedProfile}
                onChange={(e) => onProfileChange(e.target.value)}
                disabled={profileList.length === 0}
              >
                {profileList.length === 0 ? (
                  <option value="">(no profiles — open Chrome first)</option>
                ) : null}
                {profileList.map((p) => (
                  <option key={p.directoryName} value={p.directoryName}>
                    {p.displayName || p.directoryName}
                  </option>
                ))}
              </select>
            </div>
            <div style={{ flexShrink: 0, paddingBottom: 4 }}>
              <Toggle
                checked={includeKey}
                label="Include API key"
                title={TOGGLE_HELP}
                onChange={onToggleChange}
              />
            </div>
          </div>

          <pre className="wp-code" style={{ whiteSpace: 'pre-wrap' }}>{previewText}</pre>
          {includeKey ? (
            <div
              className="wp-secondary"
              style={{
                marginTop: 'var(--s-2)',
                fontSize: 'var(--fs-small)',
              }}
            >
              Unused keys expire after 48 hours.
            </div>
          ) : null}
        </div>
        <div className="wp-modal-actions">
          <button
            type="button"
            className="wp-btn"
            onClick={requestClose}
          >
            Cancel
          </button>
          <button
            type="button"
            className="wp-btn wp-btn-primary"
            onClick={handleCopy}
            disabled={submitting}
          >
            {copyLabel}
          </button>
        </div>
      </div>
    </div>
  );
}
