'use strict';

/**
 * Paired-keys store — SQLite-backed (P2 — phase 2).
 *
 * Replaces the JSON-file implementation that used to read/write
 * `<dataDir>/config/paired-keys.json` and `<dataDir>/config/pending-pairings.json`
 * on every call. Now backed by the `agents` and `pairings` tables in the
 * shared SQLite DB (see `src/db/connection.js` + `src/db/schema.sql`).
 *
 * The exported API surface is unchanged from the JSON-backed version — every
 * caller in server.js / mcp-handler.js continues to work without edits. The
 * legacy helpers `loadKeys`, `saveKeys`, `invalidateCache` are preserved as
 * thin DB-backed shims so any external tooling that imported them still
 * compiles. They are no longer the primary code path.
 *
 * ───────────────────────────────────────────────────────────────────────────
 * API key storage / hashing
 *
 * Threat model: the plain API key is 128 bits of crypto-grade randomness
 * generated by `crypto.randomUUID()` (or larger). The DB lives on the same
 * local machine as the user's browser profile, so it is not under attack
 * from network adversaries; the realistic exposure surface is incidental
 * disclosure (logs, backups, support bundles). For 128-bit random secrets
 * a rainbow-table attack is computationally absurd; the goal of hashing
 * is purely defence-in-depth so a leaked DB doesn't immediately yield
 * live credentials.
 *
 * Choice: HMAC-SHA-256 with a server-side "pepper" stored in the `config`
 * table under key `api_key_pepper` (32 random bytes, hex-encoded). HMAC-
 * SHA-256 over the pepper acts as the salt; constant-time lookup is
 * implicit because we hash the input and do an indexed lookup against
 * `agents.api_key_hash`. No KDF (argon2id/scrypt) is necessary because
 * the input has 128+ bits of entropy — work-factor hashing only matters
 * for low-entropy human passwords.
 *
 * Adds NO new dependencies (uses node:crypto).
 * ───────────────────────────────────────────────────────────────────────────
 */

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const dbModule = require('./db/connection');
const { getDataDir } = require('./service/paths');

// ───────────────────────────────────────────────────────────────────────────
// Constants (preserved from the JSON-backed implementation so behavior is
// identical to the previous module).

// Pending-pairing TTL: pending entries become "expired" after this many ms of
// inactivity. The agent can simply call request_pairing again to mint a fresh
// pairingId.
const PENDING_PAIRING_TTL_MS = 24 * 60 * 60 * 1000; // 24h
// Garbage-collect terminal / very-old entries after this many ms.
const PAIRING_HARD_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7d
// Unused-key expiry: an `agents` row whose `last_seen_at` is still null more
// than this many ms after `created_at` is auto-revoked by
// cleanupUnusedKeys().
const UNUSED_KEY_EXPIRY_MS = 48 * 60 * 60 * 1000; // 48h

// ───────────────────────────────────────────────────────────────────────────
// Pepper bootstrap

let _pepperCache = null;

/**
 * Resolve the sidecar pepper file path: `<dataDir>/secret/api-key.pepper`.
 *
 * Storing the pepper in a dedicated 0o600 file (rather than in the same
 * `webpilot.db` it peppers) is defence-in-depth against incidental DB
 * disclosure — a leaked DB file alone no longer yields the pepper an
 * attacker would need to brute-force the api_key_hash column. The proper
 * cross-platform answer is OS-native secret storage (DPAPI / Keychain /
 * libsecret via node-keytar) — see flagged finding in the audit report.
 */
function getPepperFilePath() {
  return path.join(getDataDir(), 'secret', 'api-key.pepper');
}

/**
 * Best-effort tighten the perms on the secret dir and the pepper file.
 * POSIX: 0o700 / 0o600. Windows: chmodSync only maps the read-only bit,
 * so this is informational on NTFS — the inherited %APPDATA% ACLs are
 * already owner-restricted in practice.
 */
function _restrictSecretPerms(secretDir, secretFile) {
  try { fs.chmodSync(secretDir, 0o700); } catch (_e) { /* non-fatal */ }
  try { fs.chmodSync(secretFile, 0o600); } catch (_e) { /* non-fatal */ }
}

/**
 * Read or create the API-key pepper. Storage layout:
 *
 *   - PRIMARY: `<dataDir>/secret/api-key.pepper` (32 random bytes, hex).
 *     Written 0o600 on first daemon boot, never committed, never logged.
 *   - LEGACY: `config.api_key_pepper` row inside `webpilot.db`. Older
 *     installs minted the pepper there; we keep reading it as a fallback
 *     so existing api_key_hash rows continue to validate. When we read
 *     from the legacy row we ALSO write it out to the sidecar file so
 *     subsequent boots use the hardened path.
 *
 * The pepper is process-cached after first access — it never changes for
 * the life of the install. Exposed for tests; production callers should
 * just use hashApiKey().
 *
 * @returns {string} hex-encoded pepper
 */
function getOrCreateApiKeyPepper() {
  if (_pepperCache) return _pepperCache;

  const pepperFile = getPepperFilePath();
  const secretDir = path.dirname(pepperFile);

  // 1) Sidecar file path — preferred.
  try {
    if (fs.existsSync(pepperFile)) {
      const raw = fs.readFileSync(pepperFile, 'utf8').trim();
      if (raw.length > 0) {
        _pepperCache = raw;
        // Re-assert perms in case they drifted (e.g. user copied the dir).
        _restrictSecretPerms(secretDir, pepperFile);
        return _pepperCache;
      }
    }
  } catch (e) {
    console.error('[paired-keys] sidecar pepper read failed, falling back to DB: ' + (e && e.message));
  }

  // 2) Legacy: pepper in the `config` table. Honour it for backwards-compat,
  //    then promote to the sidecar file so future boots skip this branch.
  const db = dbModule.getDb();
  const row = db.prepare('SELECT value FROM config WHERE key = ?').get('api_key_pepper');
  if (row && typeof row.value === 'string' && row.value.length > 0) {
    _pepperCache = row.value;
    try {
      fs.mkdirSync(secretDir, { recursive: true });
      fs.writeFileSync(pepperFile, _pepperCache, { encoding: 'utf8', mode: 0o600 });
      _restrictSecretPerms(secretDir, pepperFile);
      console.log('[paired-keys] promoted legacy pepper from config table to ' + pepperFile);
    } catch (e) {
      // Non-fatal: the legacy DB-stored pepper still works for this process.
      console.error('[paired-keys] could not write sidecar pepper file: ' + (e && e.message));
    }
    return _pepperCache;
  }

  // 3) First-boot mint. Generate 32 random bytes and write the sidecar with
  //    restrictive perms. Do NOT also write to the `config` table — new
  //    installs keep the pepper out of the DB entirely.
  const pepper = crypto.randomBytes(32).toString('hex');
  try {
    fs.mkdirSync(secretDir, { recursive: true });
    fs.writeFileSync(pepperFile, pepper, { encoding: 'utf8', mode: 0o600 });
    _restrictSecretPerms(secretDir, pepperFile);
    console.log('[paired-keys] minted new api_key_pepper at ' + pepperFile);
  } catch (e) {
    // Sidecar write failed (e.g. read-only volume in a CI sandbox). Fall
    // back to the DB so the daemon can still operate. This is a degraded
    // mode — log loudly.
    console.error(
      '[paired-keys] sidecar pepper write FAILED (' + (e && e.message) + ') — ' +
        'falling back to storing pepper in webpilot.db config table. ' +
        'Investigate dataDir perms.'
    );
    const nowIso = new Date().toISOString();
    db.prepare(
      'INSERT INTO config (key, value, updated_at) VALUES (?, ?, ?) ' +
        'ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at'
    ).run('api_key_pepper', pepper, nowIso);
  }
  _pepperCache = pepper;
  return _pepperCache;
}

/**
 * Hash an API key with the server pepper. Deterministic: same input + same
 * pepper always yields the same hash, so we can use it for an indexed
 * lookup in the `agents` table.
 *
 * @param {string} key plain API key
 * @returns {string} 64-char hex digest
 */
function hashApiKey(key) {
  const pepper = getOrCreateApiKeyPepper();
  return crypto.createHmac('sha256', pepper).update(String(key), 'utf8').digest('hex');
}

// Reset the pepper cache (used by tests that close + reopen the DB).
function _resetPepperCacheForTests() {
  _pepperCache = null;
}

// ───────────────────────────────────────────────────────────────────────────
// Listener registry — unchanged from the JSON-backed version.

const listeners = { approved: [], denied: [], requested: [] };

function onPairingEvent(event, fn) {
  if (!listeners[event]) listeners[event] = [];
  listeners[event].push(fn);
}

function emitPairingEvent(event, payload) {
  const fns = listeners[event] || [];
  for (const fn of fns) {
    try {
      fn(payload);
    } catch (e) {
      console.log(`[pairing] listener for "${event}" threw: ${e.message}`);
    }
  }
}

// ───────────────────────────────────────────────────────────────────────────
// Constant-time string equality. Preserved for callers that still need to
// compare two known-plaintext strings (e.g. the extension WS handshake in
// server.js compares the server's own apiKey constant against what the
// extension sent — neither is hashed, so a regular timing-safe compare is
// the right primitive).

function constantTimeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(Buffer.from(a, 'utf8'), Buffer.from(b, 'utf8'));
}

// ───────────────────────────────────────────────────────────────────────────
// Row → entry mappers. Convert raw `agents` / `pairings` DB rows back into
// the JSON-flavoured object shape that callers expect.
//
// IMPORTANT — backward compatibility contract: the previous JSON-backed
// implementation returned plain entries with fields `key`, `agentName`,
// `createdAt`, `profileId`, `lastAccessed`, and optionally `source`. Every
// caller in server.js and mcp-handler.js destructures these specific names.
// The mapper preserves them. The new field `plainKey` (only attached during
// the request that minted the key) is added so callers like `approvePairing`
// and `createPairedAgent` can return the plain key once at issuance time —
// we never persist it.

function rowToAgentEntry(row, plainKey) {
  if (!row) return null;
  const entry = {
    // `key` is the plaintext API key for the most recent caller of
    // approvePairing / addKey / createPairedAgent — those code paths attach
    // `plainKey` explicitly. For lookup paths (validateKey, listKeys) we do
    // NOT have access to the plain key — only to its hash. To preserve the
    // legacy shape we expose the hash as `key` in those cases so callers
    // can still use it as an opaque identifier (rename / revoke / touch all
    // require either the plain key OR the hash — see resolveAgentRow).
    key: plainKey || row.api_key_hash,
    agentName: row.name,
    createdAt: row.created_at,
    lastAccessed: row.last_seen_at || null,
    profileId: row.profile_id || null,
  };
  // `state` exposed so callers can distinguish active vs revoked without
  // an extra query. listKeys filters revoked rows out so this defaults to
  // 'active' in practice; validateKey only returns active rows.
  if (row.state) entry.state = row.state;
  return entry;
}

function rowToPairingEntry(row) {
  if (!row) return null;
  const entry = {
    pairingId: row.pairing_id,
    agentName: row.agent_name,
    status: row.state,
    createdAt: row.requested_at,
    expiresAt: Number(row.expires_at), // stored as numeric epoch ms
  };
  if (row.decided_at) entry.decidedAt = row.decided_at;
  if (row.metadata_json) {
    try {
      const meta = JSON.parse(row.metadata_json);
      if (meta && typeof meta === 'object') {
        if (typeof meta.apiKey === 'string') entry.apiKey = meta.apiKey;
        if (typeof meta.profileId === 'string' || meta.profileId === null) {
          entry.profileId = meta.profileId;
        }
        if (typeof meta.source === 'string') entry.source = meta.source;
      }
    } catch (_e) { /* corrupted metadata — ignore */ }
  }
  return entry;
}

/**
 * Resolve an agent row from either a plaintext API key or its hash.
 * Callers like `renameKey`, `revokeKey`, `updateProfileBinding`, `touchKey`
 * receive the plaintext key from the caller in the legacy code path, but
 * the legacy in-memory cache also handed out plaintext keys via listKeys,
 * so some UI code paths may pass the hash by mistake. Accept both — hash
 * the input, and if no row matches, fall back to treating the input as a
 * hash directly.
 */
function resolveAgentRow(keyOrHash) {
  if (typeof keyOrHash !== 'string' || keyOrHash.length === 0) return null;
  const db = dbModule.getDb();
  const hashed = hashApiKey(keyOrHash);
  let row = db
    .prepare("SELECT * FROM agents WHERE api_key_hash = ? AND state = 'active'")
    .get(hashed);
  if (row) return row;
  // Fallback: treat the input as the hash itself. listKeys() returns hash
  // as `key`, so any UI round-trip that passes that back lands here.
  row = db
    .prepare("SELECT * FROM agents WHERE api_key_hash = ? AND state = 'active'")
    .get(keyOrHash);
  return row || null;
}

// ───────────────────────────────────────────────────────────────────────────
// Legacy shims — the JSON-backed module exposed loadKeys / saveKeys /
// invalidateCache to a couple of external call sites. Those call sites have
// since been removed (the only require'r is server.js, and it only uses the
// high-level API). The shims are kept so a stale import doesn't crash:
// loadKeys returns the same shape `listKeys` returns; saveKeys/invalidateCache
// are now no-ops with a log line.

function loadKeys() {
  return listKeys();
}

function saveKeys(_keys) {
  console.log(
    '[paired-keys] saveKeys() called on the SQLite-backed module — no-op; ' +
      'callers should use the high-level helpers (addKey, renameKey, revokeKey, etc.)'
  );
}

function invalidateCache() {
  // No cache anymore — SQLite reads are already fast (single-process WAL).
}

// ───────────────────────────────────────────────────────────────────────────
// Public API

function generateKey() {
  return crypto.randomUUID();
}

/**
 * Insert a new agent row. Returns the plaintext key once — the plaintext is
 * never persisted; only the hash is stored.
 *
 * @param {string} agentName
 * @param {string|null} [profileId]
 * @param {string|null} [source]  Optional provenance tag stored in
 *   `agents` … wait, the agents table has no `source` column. We stash
 *   provenance in a future migration if it becomes important; for now the
 *   parameter is accepted (for caller compatibility) but only `web-ui-direct`
 *   provenance is informational and ignored in the DB.
 * @returns {string} the new plaintext API key
 */
function addKey(agentName, profileId = null, source = null) {
  const db = dbModule.getDb();
  const key = generateKey();
  const hash = hashApiKey(key);
  const nowIso = new Date().toISOString();
  db.prepare(
    `INSERT INTO agents (name, api_key_hash, profile_id, created_at, state)
     VALUES (?, ?, ?, ?, 'active')`
  ).run(agentName, hash, profileId || null, nowIso);
  if (source) {
    // Provenance audit: log it. The schema has no source column on `agents`;
    // adding one is a future micro-migration if we need to query by source.
    console.log(`[paired-keys] addKey: source="${source}" (informational)`);
  }
  return key;
}

/**
 * Direct UI pre-provision. Same contract as the JSON-backed version.
 */
function createPairedAgent({ agentName, profileId }) {
  const key = addKey(agentName, profileId || null, 'web-ui-direct');
  const db = dbModule.getDb();
  const row = db
    .prepare('SELECT * FROM agents WHERE api_key_hash = ?')
    .get(hashApiKey(key));
  console.log(
    `[pairing:createPairedAgent] minted direct key for agent "${agentName}" ` +
      `(profileId="${profileId || ''}", key=${key.slice(0, 8)}...)`
  );
  return {
    apiKey: key,
    agentName,
    profileId: profileId || null,
    createdAt: row ? row.created_at : new Date().toISOString(),
  };
}

/**
 * Validate an incoming API key. Returns the matching active agent entry, or
 * null if no active row matches. Hashes the input and does an indexed
 * lookup against `agents.api_key_hash`; constant-time comparison is implicit
 * (the index lookup gives O(log n) on hashed bytes regardless of which
 * agent matched).
 *
 * The returned entry's `.key` field is the api_key_hash, NOT the plaintext —
 * mirrors the JSON-backed implementation's contract that `validateKey`
 * returns "the entry" but the plaintext is no longer stored.
 */
function validateKey(apiKey) {
  if (typeof apiKey !== 'string' || apiKey.length === 0) return null;
  const row = resolveAgentRow(apiKey);
  return rowToAgentEntry(row, null);
}

function renameKey(apiKey, newName) {
  const row = resolveAgentRow(apiKey);
  if (!row) return false;
  const db = dbModule.getDb();
  db.prepare('UPDATE agents SET name = ? WHERE id = ?').run(newName, row.id);
  return true;
}

function updateProfileBinding(apiKey, profileId) {
  const row = resolveAgentRow(apiKey);
  if (!row) return false;
  const db = dbModule.getDb();
  db.prepare('UPDATE agents SET profile_id = ? WHERE id = ?').run(profileId || null, row.id);
  return true;
}

function touchKey(apiKey) {
  const row = resolveAgentRow(apiKey);
  if (!row) return;
  const db = dbModule.getDb();
  db.prepare('UPDATE agents SET last_seen_at = ? WHERE id = ?').run(
    new Date().toISOString(),
    row.id
  );
}

/**
 * Soft-delete: mark the agent row as 'revoked'. listKeys / validateKey
 * filter revoked rows out, so the agent is functionally gone but we keep
 * a revocation audit trail (per the open question in the design doc).
 */
function revokeKey(apiKey) {
  const row = resolveAgentRow(apiKey);
  if (!row) return false;
  const db = dbModule.getDb();
  db.prepare("UPDATE agents SET state = 'revoked' WHERE id = ?").run(row.id);
  return true;
}

/**
 * List all active agents in legacy-flavoured shape. `key` is the
 * api_key_hash (we never persist the plaintext).
 */
function listKeys() {
  const db = dbModule.getDb();
  const rows = db
    .prepare("SELECT * FROM agents WHERE state = 'active' ORDER BY created_at ASC")
    .all();
  return rows.map((row) => ({
    agentName: row.name,
    createdAt: row.created_at,
    lastAccessed: row.last_seen_at || null,
    key: row.api_key_hash,
    keyDisplay: row.api_key_hash.slice(0, 8) + '...',
    profileId: row.profile_id || null,
  }));
}

// ───────────────────────────────────────────────────────────────────────────
// Pairings flow

function getPairingRow(pairingId) {
  const db = dbModule.getDb();
  return db.prepare('SELECT * FROM pairings WHERE pairing_id = ?').get(pairingId);
}

function updatePairingMetadata(rowId, patch) {
  const db = dbModule.getDb();
  const current = db.prepare('SELECT metadata_json FROM pairings WHERE id = ?').get(rowId);
  let meta = {};
  if (current && current.metadata_json) {
    try { meta = JSON.parse(current.metadata_json) || {}; } catch (_e) { meta = {}; }
  }
  Object.assign(meta, patch);
  db.prepare('UPDATE pairings SET metadata_json = ? WHERE id = ?').run(
    JSON.stringify(meta),
    rowId
  );
}

function requestPairing(agentName) {
  const db = dbModule.getDb();
  const now = Date.now();
  const nowIso = new Date(now).toISOString();

  // Lazy-expire any pending row for this agentName that has aged past the TTL.
  const expirable = db
    .prepare(
      "SELECT * FROM pairings WHERE agent_name = ? AND state = 'pending' AND expires_at < ?"
    )
    .all(agentName, now);
  for (const stale of expirable) {
    db.prepare("UPDATE pairings SET state = 'expired', decided_at = ? WHERE id = ?")
      .run(nowIso, stale.id);
    console.log(
      `[pairing:requestPairing] expiring stale pending entry for "${agentName}" ` +
        `(pairingId=${stale.pairing_id}, expiresAt=${new Date(Number(stale.expires_at)).toISOString()})`
    );
  }

  // Idempotency: return any existing pending (non-expired) or approved row.
  const existingRow = db
    .prepare(
      `SELECT * FROM pairings WHERE agent_name = ? AND state IN ('pending','approved')
       ORDER BY requested_at DESC LIMIT 1`
    )
    .get(agentName);
  if (existingRow) {
    const entry = rowToPairingEntry(existingRow);
    console.log(
      `[pairing:requestPairing] returning existing ${entry.status} entry ` +
        `for agent "${agentName}" (pairingId=${entry.pairingId})`
    );
    return {
      pairingId: entry.pairingId,
      status: entry.status,
      apiKey: entry.apiKey,
      created: false,
    };
  }

  const pairingId = crypto.randomUUID();
  const expiresAt = now + PENDING_PAIRING_TTL_MS;
  db.prepare(
    `INSERT INTO pairings (pairing_id, agent_name, requested_at, expires_at, state)
     VALUES (?, ?, ?, ?, 'pending')`
  ).run(pairingId, agentName, nowIso, expiresAt);

  const entry = {
    pairingId,
    agentName,
    status: 'pending',
    createdAt: nowIso,
    expiresAt,
  };
  console.log(
    `[pairing:requestPairing] created new pending entry for agent "${agentName}" ` +
      `(pairingId=${pairingId}, expiresAt=${new Date(expiresAt).toISOString()})`
  );
  emitPairingEvent('requested', entry);
  return { pairingId, status: 'pending', created: true };
}

function checkPairingStatus(pairingId) {
  const row = getPairingRow(pairingId);
  if (!row) {
    console.log(`[pairing:checkPairingStatus] pairingId=${pairingId} not found`);
    return null;
  }
  // Lazy expiration: a pending row past expiresAt becomes 'expired' on read.
  if (row.state === 'pending' && Number(row.expires_at) < Date.now()) {
    const nowIso = new Date().toISOString();
    const db = dbModule.getDb();
    db.prepare("UPDATE pairings SET state = 'expired', decided_at = ? WHERE id = ?")
      .run(nowIso, row.id);
    console.log(
      `[pairing:checkPairingStatus] pairingId=${pairingId} expired ` +
        `(expiresAt=${new Date(Number(row.expires_at)).toISOString()}) — marking expired`
    );
    return { status: 'expired' };
  }
  const entry = rowToPairingEntry(row);
  console.log(`[pairing:checkPairingStatus] pairingId=${pairingId} status=${entry.status}`);
  const result = { status: entry.status };
  if (entry.apiKey) {
    result.apiKey = entry.apiKey;
    // SECURITY: the plaintext apiKey is stored in pairings.metadata_json so the
    // polling agent can retrieve it after approval. Once we have handed it back
    // to the caller, clear it from the row so the plaintext does not persist
    // at rest indefinitely. Subsequent polls for the same pairingId will see
    // status='approved' with no apiKey field — the agent is expected to have
    // stored the key on its first successful read. The agents row (api_key_hash
    // only) is the durable record.
    try {
      const db = dbModule.getDb();
      // Preserve profileId / source / etc. — only strip apiKey.
      let meta = {};
      try { meta = JSON.parse(row.metadata_json) || {}; } catch (_e) { meta = {}; }
      if (typeof meta === 'object' && meta !== null && 'apiKey' in meta) {
        delete meta.apiKey;
        db.prepare('UPDATE pairings SET metadata_json = ? WHERE id = ?')
          .run(JSON.stringify(meta), row.id);
        console.log(
          `[pairing:checkPairingStatus] cleared plaintext apiKey from pairings.metadata_json ` +
            `for pairingId=${pairingId} (one-time retrieval consumed)`
        );
      }
    } catch (e) {
      // Non-fatal — the caller already has the key; log so we know if the
      // cleanup is silently failing in production.
      console.error(
        `[pairing:checkPairingStatus] failed to clear plaintext apiKey for pairingId=${pairingId}: ` +
          (e && e.message)
      );
    }
  }
  return result;
}

function approvePairing(pairingId, options = {}) {
  const profileId = (options && options.profileId) || null;
  const row = getPairingRow(pairingId);
  if (!row) {
    console.log(`[pairing] approvePairing: pairingId=${pairingId} not found`);
    return null;
  }
  if (row.state === 'approved') {
    console.log(
      `[pairing] approvePairing: pairingId=${pairingId} already approved, returning existing`
    );
    return rowToPairingEntry(row);
  }
  if (row.state === 'denied' || row.state === 'expired') {
    console.log(
      `[pairing] approvePairing: pairingId=${pairingId} is ${row.state}, cannot approve`
    );
    return null;
  }

  // Mint a real API key — this writes a new row to `agents` and returns the
  // plaintext key. We persist it on the pairings row's metadata_json so the
  // UI's "approved — here is the key" flow keeps working.
  const key = addKey(row.agent_name, profileId);
  const nowIso = new Date().toISOString();
  const db = dbModule.getDb();

  // Resolve the agent row we just created so we can link approved_agent_id.
  const agentRow = db
    .prepare('SELECT id FROM agents WHERE api_key_hash = ?')
    .get(hashApiKey(key));
  const approvedAgentId = agentRow ? agentRow.id : null;

  db.prepare(
    `UPDATE pairings
       SET state = 'approved', decided_at = ?, approved_agent_id = ?, metadata_json = ?
       WHERE id = ?`
  ).run(
    nowIso,
    approvedAgentId,
    JSON.stringify({ apiKey: key, profileId: profileId || null }),
    row.id
  );

  const entry = {
    pairingId: row.pairing_id,
    agentName: row.agent_name,
    status: 'approved',
    createdAt: row.requested_at,
    expiresAt: Number(row.expires_at),
    apiKey: key,
    profileId: profileId || null,
    decidedAt: nowIso,
  };
  console.log(
    `[pairing] approvePairing: pairingId=${pairingId} approved for agent "${row.agent_name}", ` +
      `key=${key.slice(0, 8)}..., profileId="${profileId || ''}"`
  );
  emitPairingEvent('approved', entry);
  return entry;
}

function denyPairing(pairingId) {
  const row = getPairingRow(pairingId);
  if (!row) {
    console.log(`[pairing] denyPairing: pairingId=${pairingId} not found`);
    return null;
  }
  if (row.state === 'denied') {
    console.log(`[pairing] denyPairing: pairingId=${pairingId} already denied`);
    return rowToPairingEntry(row);
  }
  if (row.state === 'approved' || row.state === 'expired') {
    console.log(
      `[pairing] denyPairing: pairingId=${pairingId} is ${row.state}, cannot deny`
    );
    return null;
  }
  const nowIso = new Date().toISOString();
  const db = dbModule.getDb();
  db.prepare("UPDATE pairings SET state = 'denied', decided_at = ? WHERE id = ?")
    .run(nowIso, row.id);
  const entry = {
    pairingId: row.pairing_id,
    agentName: row.agent_name,
    status: 'denied',
    createdAt: row.requested_at,
    expiresAt: Number(row.expires_at),
    decidedAt: nowIso,
  };
  console.log(
    `[pairing] denyPairing: pairingId=${pairingId} denied for agent "${row.agent_name}"`
  );
  emitPairingEvent('denied', entry);
  return entry;
}

function listPendingPairings() {
  const db = dbModule.getDb();
  const rows = db
    .prepare("SELECT * FROM pairings WHERE state = 'pending' ORDER BY requested_at DESC")
    .all();
  return rows.map(rowToPairingEntry);
}

function listAllPairings() {
  const db = dbModule.getDb();
  const rows = db
    .prepare('SELECT * FROM pairings ORDER BY requested_at DESC')
    .all();
  return rows.map(rowToPairingEntry);
}

// ───────────────────────────────────────────────────────────────────────────
// Periodic maintenance

function cleanupExpiredPairings() {
  const db = dbModule.getDb();
  const now = Date.now();
  const cutoff = now - PAIRING_HARD_TTL_MS;
  const nowIso = new Date(now).toISOString();

  // Pending past expiresAt → 'expired'
  const expireRes = db
    .prepare(
      "UPDATE pairings SET state = 'expired', decided_at = ? WHERE state = 'pending' AND expires_at < ?"
    )
    .run(nowIso, now);

  // Hard-drop: anything created longer ago than hard TTL.
  // requested_at is ISO 8601; SQLite's julianday() comparison works on ISO 8601
  // strings, but the simplest cross-platform path is to compute the cutoff ISO
  // here in JS.
  const cutoffIso = new Date(cutoff).toISOString();
  const dropRes = db
    .prepare('DELETE FROM pairings WHERE requested_at < ?')
    .run(cutoffIso);

  const remaining = db.prepare('SELECT COUNT(*) AS c FROM pairings').get().c;
  if (expireRes.changes || dropRes.changes) {
    console.log(
      `[pairing:cleanup] expired=${expireRes.changes} dropped=${dropRes.changes} kept=${remaining}`
    );
  }
  return { expired: expireRes.changes, dropped: dropRes.changes, kept: remaining };
}

function cleanupOldPairings(maxAgeDays = 7) {
  const db = dbModule.getDb();
  const cutoff = Date.now() - maxAgeDays * 24 * 60 * 60 * 1000;
  const cutoffIso = new Date(cutoff).toISOString();
  // Drop denied/expired rows older than the cutoff. Approved/pending are
  // preserved — same touch-matrix as the JSON-backed implementation.
  const res = db
    .prepare(
      `DELETE FROM pairings
         WHERE state IN ('denied','expired')
           AND COALESCE(decided_at, requested_at) < ?`
    )
    .run(cutoffIso);
  const remaining = db.prepare('SELECT COUNT(*) AS c FROM pairings').get().c;
  if (res.changes > 0) {
    console.log(
      `[pairing:cleanupOldPairings] removed=${res.changes} kept=${remaining} ` +
        `(maxAgeDays=${maxAgeDays}, terminal-only: denied + expired)`
    );
  }
  return { removed: res.changes, kept: remaining };
}

function cleanupUnusedKeys(maxAgeMs = UNUSED_KEY_EXPIRY_MS) {
  const db = dbModule.getDb();
  const cutoff = Date.now() - maxAgeMs;
  const cutoffIso = new Date(cutoff).toISOString();
  // Active rows that have never been touched and were created before the cutoff.
  const stale = db
    .prepare(
      `SELECT id, name, api_key_hash, created_at FROM agents
         WHERE state = 'active' AND last_seen_at IS NULL AND created_at < ?`
    )
    .all(cutoffIso);
  if (stale.length === 0) return 0;
  const revokeStmt = db.prepare("UPDATE agents SET state = 'revoked' WHERE id = ?");
  for (const row of stale) {
    const keyDisplay = (row.api_key_hash || '').slice(0, 8) + '...';
    console.log(
      `[paired-keys:cleanupUnusedKeys] revoked unused key ${keyDisplay} ` +
        `for agent "${row.name}" (created ${row.created_at}, never accessed)`
    );
    revokeStmt.run(row.id);
  }
  return stale.length;
}

// ───────────────────────────────────────────────────────────────────────────
// Module exports — surface is identical to the JSON-backed version.

module.exports = {
  loadKeys,
  saveKeys,
  invalidateCache,
  generateKey,
  addKey,
  createPairedAgent,
  validateKey,
  renameKey,
  updateProfileBinding,
  touchKey,
  revokeKey,
  listKeys,
  // Async pairing
  requestPairing,
  checkPairingStatus,
  approvePairing,
  denyPairing,
  listPendingPairings,
  listAllPairings,
  cleanupExpiredPairings,
  cleanupOldPairings,
  cleanupUnusedKeys,
  onPairingEvent,
  // Helpers exposed for other auth paths and tests.
  constantTimeEqual,
  hashApiKey,
  getOrCreateApiKeyPepper,
  _resetPepperCacheForTests,
  // Constants
  UNUSED_KEY_EXPIRY_MS,
};
